account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='signin'),
    path('logout/', views.signout, name='logout'),
]

cocoding/urls.py
from django.urls import path
from . import views

app_name = 'cocoding'

urlpatterns = [
    path('', views.PostList.as_view(), name='post_list'),
    path('newstudy/', views.post_create, name='post_create'),
    path('<int:pk>/', views.PostDetail.as_view()),
    path('<int:pk>/new_comment/', views.new_comment, name="new_comment"),
    path('post_delete/<int:pk>/', views.post_delete, name="post_delete"),
    path('comment_delete/<int:pk>/', views.comment_delete, name="comment_delete"),
    path('post_update/<int:pk>/', views.PostUpdate.as_view()),
    path('comment_update/<int:pk>/', views.CommentUpdate.as_view(), name="comment_update"),
    path('search/<str:q>/', views.PostSearch.as_view(), name='post_search'),
    path('set_recruit/<int:pk>/', views.set_recruit, name="set_recruit"),

    # path('post/<slug:slug>/', views.detail_view, name='detail'),
    # path('tag/<slug:slug>/', views.tagged, name='taged'),
    #path('newstudy/', views.PostCreate.as_view(), name='post_create'),
]

cocoding_prj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('cocoding.urls')),
    path('account/', include('account.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('admin/', admin.site.urls),
]

cocoding/models.py
from django.db import models
from account.models import User
from taggit.managers import TaggableManager


class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    tags = TaggableManager()
    slug = models.SlugField(unique=False, max_length=100, blank=True)
    recruiting = models.BooleanField(default=True)


    def __str__(self):
        return f'[{self.pk}] {self.title} :: {self.author}'

    def get_absolute_url(self):
        return f'/{self.pk}/'


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return f'{self.author}::{self.content}'

    def get_absolute_url(self):
        return f'{self.post.get_absolute_url()}#comment-{self.pk}'

cocoding/forms.py
from django import forms 
from .models import Post, Comment
from django_summernote.widgets import SummernoteWidget


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'tags',)
        widgets = {
            'content': SummernoteWidget(),
        }

    def clean_title(self):
        title = self.cleaned_data.get('title')
        title_length = len(title)
        if title_length>50:
            raise forms.ValidationError('제목은 50자를 넘을 수 없습니다.')
        return title

    def clean_content(self):
        content = self.cleaned_data.get('content')
        content_length = len(content)
        if content_length>5000:
            raise forms.ValidationError('내용은 5,000자를 넘을 수 없습니다.')
        return content

    def clean_tags(self):
        tags = self.cleaned_data.get('tags', [])
        if len(tags) > 4:
            raise forms.ValidationError('태그는 최대 4개까지 가능합니다.', code='invalid')
        return tags


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

cocoding/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from .models import Post, Comment
from django.core.exceptions import PermissionDenied
from .forms import PostForm, CommentForm
from django.views.generic import UpdateView, ListView, DetailView
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render, redirect
from django.utils.text import slugify
from django.http import JsonResponse
from django.db.models import Q


class PostList(ListView):
    model = Post
    ordering = '-pk'
    paginate_by = 8
    def get_context_data(self, **kwargs):
        context = super(PostList, self).get_context_data()
        context['paginator'] = Paginator(Post.objects.all().order_by('-pk'), 8)
        return context


@login_required(login_url='/account/signin/')
def post_create(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            current_user = request.user
            form.instance.author = current_user
            newpost = form.save(commit=False)
            newpost.slug = slugify(newpost.title)
            newpost.save()
            form.save_m2m()
            return redirect('cocoding:post_list')
    else:
        form = PostForm()
    context = {'form': form}    
    return render(request, 'cocoding/post_form.html', context)


class PostDetail(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data()
        return context


def post_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.user.is_authenticated and request.user == post.author:
        post.delete()
        return redirect('cocoding:post_list')
    else:
        raise PermissionDenied


def new_comment(request, pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=pk)
        if request.method=='POST':
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.post = post
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url())
        else:
            return redirect(post.get_absolute_url())
        
    else:
        raise PermissionDenied


def comment_delete(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post = comment.post
    if request.user.is_authenticated and request.user == comment.author:
        comment.delete()
        return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied


class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'cocoding/post_update_form.html'
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(PostUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied


class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment
    form_class = CommentForm
    template_name = 'cocoding/comment_update_form.html'
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(CommentUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied



class PostSearch(PostList):
    paginate_by = 8
    
    def get_queryset(self):
        q = self.kwargs['q']
        post_list = Post.objects.filter(
            Q(title__contains=q) | Q(tags__name__contains=q)
        ).distinct().order_by('-pk')
        return post_list
    
    def get_context_data(self, **kwargs):
        context = super(PostSearch, self).get_context_data()
        q = self.kwargs['q']
        context['search_info'] = f'Search: {q} ({self.get_queryset().count()})'
        context['paginator'] = Paginator(self.get_queryset(), 8)
        
        return context
    
    

def set_recruit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.user.is_authenticated and request.user == post.author:
        post.recruiting = not post.recruiting
        post.save()
        return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied

cocoding/templates/cocoding/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="/static/cocoding/dist/css/bootstrap.min.css">
  <title>COCODING | 함께, 코딩해요</title>
</head>
<body>
  {% include 'cocoding/navbar.html' %}
  {% block content %}
  {% endblock %}
  {% include 'cocoding/footer.html' %}
</body>
<script src="https://kit.fontawesome.com/edc45c71bc.js" crossorigin="anonymous"></script>
<script src="/static/cocoding/dist/js/jquery-3.6.0.min.js"></script>
<script src="/static/cocoding/dist/css/bootstrap.min.css"></script>
<script src="/static/cocoding/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
</html>

cocoding/templates/cocoding/comment_form.html
<div class="container my-3">
    <h5 class="my-3 border-bottom pb-2 fw-bolder">댓글 작성</h5>
    <form method="post" class="post-form" action="{{post.get_absolute_url}}new_comment/">
        {% csrf_token %}
        <div class="form-group mb-3">
            <textarea required="required" name="content" class="form-control" id="content" rows="10" value="{{ form.content.value|default_if_none:'' }}"></textarea>
            <span style="color:red">{{ form.content.errors }}</span>
        </div>
        <button type="submit" class="btn btn-primary">댓글 등록</button>
    </form>
</div>

cocoding/templates/cocoding/comment_update_form.html
{% extends 'cocoding/base.html' %}
{% block content %}
<div class="container my-3">
    <h5 class="my-3 border-bottom pb-2 fw-bolder">댓글 수정</h5>
    <form method="post" class="post-form">
        {% csrf_token %}
        <div class="form-group mb-3">
            <textarea required="required" name="content" class="form-control" id="content" rows="10" value="{{ form.content.value | default_if_none:'' }}">{{form.content.value}}</textarea>
            <span style="color:red">{{ form.content.errors }}</span>
        </div>
        <button type="submit" class="btn btn-primary">완료</button>
    </form>
</div>
{% endblock %}

cocoding/templates/cocoding/footer.html
<footer class="py-5">
    <div class="container">
        <p class="m-0 text-center text-muted">Copyright &copy; COCODING 2022</p>
    </div>
</footer>

cocoding/templates/cocoding/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="/"><span class="text-primary fw-bolder fs-1">CO</span><span class="fw-bolder fs-1">CODING</span></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
      aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cocoding:post_create' %}">글쓰기</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account:logout' %}">로그아웃</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account:signup' %}">회원가입</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account:signin' %}">로그인</a>
          <div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  <div class="text-center">
                    <div class="form-signin container">
                      <form method="post" class="post-form" action="{% url 'account:signin' %}">
                        {% csrf_token %}
                        <div class="form-floating">
                          <input type="email" class="form-control mb-3" name="email" id="email" placeholder="name@example.com"
                          value="{{ form.email.value|default_if_none:'' }}">
                          <label for="email" >이메일</label>
                        </div>
                        <div class="form-floating">
                          <input type="password" class="form-control mb-3" name="password" id="password" placeholder="Password"
                            value="{{ form.password.value|default_if_none:'' }}">
                          <label for="password">비밀번호</label>
                        </div>
                        <div class="d-grid gap-3">
                          <button class="w-100 btn btn-lg btn-primary" type="submit">로그인</button>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

cocoding/templates/cocoding/post_detail.html
{% extends 'cocoding/base.html' %}
{% block content %}

<div class="container mt-3 w-75">
    <div id="title">
        <div class="fw-bolder fs-2">
            {{post.title}}
        </div>
        <div class="float-end fs-6 fw-bold text-muted ">
            {% if post.author == user %}
            {% if post.recruiting %}
            <a class="btn btn-primary btn-sm" href="/set_recruit/{{post.pk}}/">모집중</a>
            {% else %}
            <a class="btn btn-primary btn-sm" href="/set_recruit/{{post.pk}}/">모집완료</a>
            {% endif %}
            {% else %}
            {% if post.recruiting %}
            <a class="btn btn-primary btn-sm">모집중</a>
            {% else %}
            <a class="btn btn-primary btn-sm">모집완료</a>
            {% endif %}
            {% endif %}
        </div>
        <div class="mt-1">
            <span class="fw-bold">{{post.author.nickname}}</span>
            <span class="text-muted">·&nbsp;{{post.created_at|date:'Y-m-d'}}</span>
        </div>
        <div class="mt-2 fw-bold text-muted">
            {% if user.is_authenticated and post.author == user %}
            <span style="cursor:pointer;" onclick="location.href='/post_update/{{post.pk}}/'">수정</span>
            <!-- <span style="cursor:pointer;" onclick="location.href='/post_delete/{{post.pk}}/'">삭제</span> -->
            <span style="cursor:pointer;" data-bs-toggle="modal" data-bs-target="#postDelete">삭제</span>
            <div class="modal fade" id="postDelete" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="postDeleteLabel">게시물 삭제</h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      게시물을 삭제하시겠습니까?
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">취소</button>
                      <a role="button" class="btn btn-primary" href="/post_delete/{{post.pk}}/">확인</a>
                    </div>
                  </div>
                </div>
              </div>
            {% endif %}
        </div>
        <hr/>
        <div id="content">
            {{post.content | safe}}
        </div>
        <hr />
        <div class="bg-light" id="tag">
            <span class="text-muted">연관태그</span>
            {% for tag in post.tags.all %}
            <a href="{% url 'cocoding:post_search' tag %}"><span class="badge rounded-pill bg-secondary">#{{ tag }}</span></a>
            {% endfor %}
        </div>
        <hr />
        <div id="comment">
            <!-- Comments section-->
            <section class="mb-5">
                <div class="card bg-light">
                    <div class="card-body">
                        <!-- Single comment-->
                        {% if post.comment_set.exists %}
                        {% for comment in post.comment_set.iterator %}
                        <div class="d-flex">
                            <div class="ms-3">
                                <div class="fw-bold mb-3">
                                    {{comment.author.nickname}}&nbsp;&nbsp;
                                    <small class="text-muted">{{comment.created_at | date:'Y-m-d'}}</small>
                                </div>
                                {{comment.content | linebreaks | safe}}
                            </div>
                            {% if user.is_authenticated and comment.author == user %}
                                <div class="float-end ms-3">
                                    <a role="button" class="btn btn-sm btn-secondary"
                                        id="comment-{{comment.pk}}-update-btn"
                                        href="/comment_update/{{comment.pk}}/">수정</a>
                                    <a role="button" class="btn btn-sm btn-secondary"
                                        id="comment-{{comment.pk}}-delete-modal-btn" href="#" data-bs-toggle="modal"
                                        data-bs-target="#deleteCommentModal-{{comment.pk}}">삭제</a>
                                </div>
                                <div class="modal fade" id="deleteCommentModal-{{comment.pk}}" role="dialog"
                                    tabindex="-1" aria-labelledby="deleteCommentModalLabel" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="deleteModalLabel">댓글 삭제</h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                    aria-label="Close">
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                댓글을 삭제하시겠습니까?
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary"
                                                    data-bs-dismiss="modal">취소</button>
                                                <a role="button" class="btn btn-primary"
                                                    href="/comment_delete/{{comment.pk}}/">확인</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {% endif %}
                        </div>
                        <hr />
                        {% endfor %}
                        {% endif %}
                        {% if user.is_authenticated %}
                        <!-- Comment form-->
                        {% include 'cocoding/comment_form.html' %}
                        {% else %}
                        <div class="d-grid gap-2">
                            <a role="button" class="mb-4 btn btn-outline-secondary btn-block btn-sm"
                                href="{% url 'account:signin' %}">
                                로그인 후 댓글 작성하기</a>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </section>
        </div>
    </div>


    {% endblock %}

cocoding/templates/cocoding/post_form.html
{% extends 'cocoding/base.html' %}
{% block content %}
<link rel="stylesheet" href="/static/cocoding/dist/css/tagsinput.css" />

<div class="container my-3 w-75">
    <h5 class="my-3 border-bottom pb-2 fw-bolder">게시글 작성</h5>
    <form method="post" class="post-form" action="{% url 'cocoding:post_create' %}">
        {% csrf_token %}
        <div class="form-group mb-3">
            <label for="title">제목</label>
            <input required="required" type="text" class="form-control" placeholder="제목을 입력해주세요" name="title"
                id="title" value="{{ form.title.value|default_if_none:'' }}">
            <span style="color:red">{{ form.title.errors }}</span>
        </div>

        <div class="form-group mb-3">
            <label>태그</label>
            <input type="text" data-role="tagsinput" class="form-control" name="tags" id="tags" value="{{ form.tags.value|default_if_none:'' }}">
            <span style="color:red">{{ form.tags.errors }}</span>
        </div>

        <div class="form-group mb-3">
            <label>내용</label>
            {{form.content}}
            <span style="color:red">{{ form.content.errors }}</span>
        </div>

        <button class="btn btn-primary" type="submit">작성완료</button>

    </form>
</div>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="/static/cocoding/dist/js/tagsinput.js"></script>
<script>
$("#post-form").submit(function(e){
        e.preventDefault();
        });
</script>
{% endblock %}

cocoding/templates/cocoding/post_list.html
{% extends 'cocoding/base.html' %}
{% block content %}

<head>
  <meta name="description" content="">
  <!-- Bootstrap core CSS -->
  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>
</head>

<div>
  <main>
    <section class="text-center bg-dark text-white mb-5" style="height: 250px;">
      <div class="row py-5">
        <div class="col-lg-6 col-md-8 mx-auto">
          <h1 class="fw-light">함께 성장할 스터디를 모집해보세요</h1>
          <p class="lead text-muted">코딩메이트를 구하는 가장 쉬운방법!</p>
        </div>
      </div>
    </section>


    <div>
      <hr class="mx-3 mb-4" />
      <div class="row mx-2 g-3 mb-4">
        <div class="col-5">
          <input aria-describedby="button-search" type="text" class="form-control mb-2" id="search-input"
            placeholder="관심 스터디를 검색해보세요!">
        </div>
        <div class="col-3">
          <button id="button-search" type="button" class="btn btn-primary mb-2" onclick="searchPost();">검색</button>
        </div>
      </div>
      {% if post_list %}
      <div class="row row-cols-1 row-cols-md-2 g-3 mx-2">
        {% for post in post_list %}
        <div class="col">
          <div class="card border-primary">
            <div class="card-header">
              {% if post.recruiting %}
              <span class="badge bg-primary">모집중</span>
              {% else %}
              <span class="badge bg-secondary">모집완료</span>
              {% endif %}
              <div class="float-end">
                {% if post.tags %}
                {% for tag in post.tags.all %}
                <a href="{% url 'cocoding:post_search' tag %}"><span class="badge bg-secondary">#{{ tag }}</span></a>
                {% endfor %}
                {% endif %}
              </div>
            </div>
            <a href="{{post.get_absolute_url}}" class="card-body text-dark" style="text-decoration:none">
              <h5 class="card-title fw-bold">{{post.title | truncatechars:17}}</h5>
              <h6 class="text-muted mt-3">{{post.author.nickname}}&nbsp;·&nbsp;{{post.created_at |date:'Y-m-d'}}
                <span class="float-end"><i
                    class="far fa-comment-dots"></i>&nbsp;<span>{{post.comment_set.count}}</span></span>
              </h6>
            </a>
          </div>
        </div>
        {% endfor %}
      </div>
      {% endif %}
    </div>
  </main>
</div>


<nav aria-label="Pagination">
  <ul class="pagination justify-content-center my-5">
    {% if page_obj.has_previous %}

    <li class="page-item">
      <a class="page-link" href="?page={{page_obj.previous_page_number}}">이전</a>
    </li>

    {% endif %}
    {% for page in paginator.page_range %}
    {% if page_obj.number == page %}
    <li class="page-item active"><a class="page-link" href="?page={{page}}">{{page}}</a></li>
    {% else %}
    <li class="page-item"><a class="page-link" href="?page={{page}}">{{page}}</a></li>
    {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{page_obj.next_page_number}}">다음</a>
    </li>
    {% endif %}
  </ul>
</nav>
<hr />

<script>
  function searchPost() {
    let searchValue = document.getElementById('search-input').value.trim();
    if (searchValue.length > 1) {
      location.href = "/search/" + searchValue + "/";
    }
    else {
      alert('검색어(' + searchValue + ')가 너무 짧습니다.');
    }
  };

  document.getElementById('search-input').addEventListener('keyup', function (event) {
    if (event.key === 'Enter') {
      searchPost();
    }
  });
</script>




{% endblock %}

cocoding/templates/cocoding/post_update_form.html
{% extends 'cocoding/base.html' %}
{% block content %}
<link rel="stylesheet" href="/static/cocoding/dist/css/tagsinput.css" />

<div class="container my-3 w-75">
    <h5 class="my-3 border-bottom pb-2 fw-bolder">게시글 수정</h5>
    <form method="post" class="post-form">
        {% csrf_token %}
        <div class="form-group mb-3">
            <label for="title">제목</label>
            <input required="required" type="text" class="form-control" placeholder="제목을 입력해주세요" name="title"
                id="title" value="{{ form.title.value|default_if_none:'' }}">
            <span style="color:red">{{ form.title.errors }}</span>
        </div>

        <div class="form-group mb-3">
            <label>태그</label>
            <input type="text" data-role="tagsinput" class="form-control" name="tags" id="tags" value="{% for tag in post.tags.all %}{{ tag }},{% endfor %}">
            <span style="color:red">{{ form.tags.errors }}</span>
        </div>

        <div class="form-group mb-3">
            <label>내용</label>
            {{form.content}}
            <span style="color:red">{{ form.content.errors }}</span>
        </div>
        
        <button class="btn btn-primary" type="submit">완료</button>
        
    </form>
</div>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="/static/cocoding/dist/js/tagsinput.js"></script>
<script>
$("#post-form").submit(function(e){
        e.preventDefault();
        });
</script>
{% endblock %}

cocoding/templates/cocoding/test.html
{% extends 'cocoding/base.html' %}
{% block content %}
<ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home" type="button" role="tab" aria-controls="home" aria-selected="true">Home</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile" type="button" role="tab" aria-controls="profile" aria-selected="false">Profile</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="messages-tab" data-bs-toggle="tab" data-bs-target="#messages" type="button" role="tab" aria-controls="messages" aria-selected="false">Messages</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="settings-tab" data-bs-toggle="tab" data-bs-target="#settings" type="button" role="tab" aria-controls="settings" aria-selected="false">Settings</button>
    </li>
  </ul>
  
  <div class="tab-content">
    <div class="tab-pane active" id="home" role="tabpanel" aria-labelledby="home-tab">...</div>
    <div class="tab-pane" id="profile" role="tabpanel" aria-labelledby="profile-tab">...</div>
    <div class="tab-pane" id="messages" role="tabpanel" aria-labelledby="messages-tab">...</div>
    <div class="tab-pane" id="settings" role="tabpanel" aria-labelledby="settings-tab">...</div>
  </div>
  
  <script>
    var firstTabEl = document.querySelector('#myTab li:last-child button')
    var firstTab = new bootstrap.Tab(firstTabEl)
  
    firstTab.show()
  </script>

{% endblock %}